# SwiftLint Configuration for swift-standards
# Optimized for library/framework development

# Disabled rules
disabled_rules:
  - explicit_type_interface  # Too strict - type inference is idiomatic Swift
  - explicit_init  # Prefer MyType() over MyType.init()
  - extension_access_modifier  # We prefer access on members, not on extension
  - explicit_acl  # Too verbose - require internal on everything
  - todo  # TODOs are fine in development
  - force_cast  # Sometimes needed in tests
  - force_try  # Sometimes needed in tests
  - line_length  # No line length restrictions
  - file_length  # No file length restrictions
  - cyclomatic_complexity  # Lookup tables and domain logic often have inherent complexity
  - function_parameter_count  # Time/Date initializers legitimately need many parameters
  - large_tuple  # Component tuples are acceptable for internal use
  - file_header  # No consistent file header pattern across packages
  - missing_docs  # Documentation is handled via code comments, not strictly required
  - identifier_name  # Swift Testing uses backticks and descriptive names
  - type_name  # Swift Testing @Suite uses descriptive names with spaces
  - optional_data_string_conversion  # False positive on [UInt8] conversion
  - for_where  # Not always clearer than for+if pattern
  - contains_over_first_not_nil  # False positives on custom firstIndex implementations

# Opt-in rules for library quality
opt_in_rules:
  # Code quality
  - sorted_imports  # Keep imports organized
  - closure_spacing  # Consistent closure formatting
  - contains_over_first_not_nil  # Performance optimization
  - empty_count  # Use .isEmpty instead of .count == 0
  - first_where  # Performance optimization
  - last_where  # Performance optimization

  # Style
  - multiline_parameters  # Better formatted parameter lists
  - operator_usage_whitespace  # Consistent operator spacing
  - vertical_parameter_alignment_on_call  # Aligned parameters

  # Safety
  - array_init  # Safer array initialization
  - fatal_error_message  # Require messages in fatalError
  - implicitly_unwrapped_optional  # Avoid IUOs where possible
  - legacy_random  # Use modern random APIs
  - overridden_super_call  # Ensure super is called

# Paths
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm

# Rule configurations

# Allow longer functions for complex performance logic
function_body_length:
  warning: 60
  error: 100

# Allow larger types for comprehensive test suites
type_body_length:
  warning: 400
  error: 600

# Nesting depth
nesting:
  type_level: 2


# Custom rules
custom_rules:
  # Ensure performance-critical code is marked
  performance_comment:
    name: "Performance Comment"
    regex: '@inline'
    message: "Consider documenting why @inline is needed"
    severity: warning
