disabled_rules:
  - line_length
  - trailing_comma
  - redundant_discardable_let
  - identifier_name  # Allow short variable names (i, x, y, etc.)
  - large_tuple  # Allow tuples with more than 2 members
  - optional_data_string_conversion  # False positive with String(decoding:as:)
  - for_where  # False positives when for loops have complex logic, not just filtering
  - todo  # Allow TODO comments for tracking future work
  - type_body_length  # Don't enforce maximum type body length

opt_in_rules:
  - explicit_init
  - closure_spacing
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - operator_usage_whitespace
  - overridden_super_call

included:
  - Sources
  - Tests

excluded:
  - .build
  - Carthage
  - Pods
  - fastlane

# File length settings
file_length:
  warning: 800
  error: 1000
  ignore_comment_only_lines: true

# Function body length settings
function_body_length:
  warning: 100
  error: 120

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 20

# Type name settings - very permissive to allow test suite names with spaces/special chars
type_name:
  allowed_symbols: ["_", "-", " ", "+", ".", ":", "(", ")", "[", "]"]
  validates_start_with_lowercase: false
  min_length: 1
  max_length: 100
